services:
    Symfony\Component\EventDispatcher\EventDispatcherInterface:
        class: Symfony\Component\EventDispatcher\EventDispatcher

    application:
        public: true
        class: Symfony\Component\Console\Application
        calls:
            - [setCommandLoader, ['@console.command_loader']]
            - [setDispatcher, ['@Symfony\Component\EventDispatcher\EventDispatcherInterface']]

    _defaults:
            autowire: true      # Automatically injects dependencies in your services.
            autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
            public: false

    Application\:
        resource: 'src/*'
